SELECT * FROM counties;
SELECT * FROM crops;
SELECT * FROM household_stats;
SELECT * FROM population;
SELECT * FROM v_population_by_gender;
SELECT * FROM  v_crops_by_county;
SELECT * FROM v_pop_per_household;
SELECT * FROM v_farming_participation ;
SELECT * FROM v_crop_diversity ;
SELECT * FROM v_gender_ratio ;
SELECT * FROM v_primary_crop ;
SELECT * FROM v_household_stats ;